import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Headertop from "./components/Headertop";
import HeaderMain from "./components/HeaderMain";
import Navbar from "./components/Navbar";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import NewProducts from "./components/NewProducts";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Haider.com:Home:",
  description: "Generated by Haider Ali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Headertop />
      <HeaderMain/>
      <Navbar/>
      {children}
        </body>
    </html>
  );
}
